# Generated by Django 4.2.30 on 2026-06-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0124_helpdeskrequestassignee_helpdeskrequest_assignees'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpdeskportal',
            name='enable_chat',
            field=models.BooleanField(default=True),
        ),
    ]
