# Generated by Django 4.2.30 on 2026-06-17 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0125_helpdeskportal_enable_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpdeskportal',
            name='enable_chat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='helpdeskportal',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project'),
        ),
        migrations.AlterField(
            model_name='helpdeskrequest',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project'),
        ),
        migrations.AlterField(
            model_name='helpdeskrequestassignee',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project'),
        ),
        migrations.AlterField(
            model_name='helpdeskrequestcomment',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project'),
        ),
        migrations.AlterField(
            model_name='helpdeskrequestissue',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project'),
        ),
        migrations.CreateModel(
            name='HelpdeskRequestIntakeIssue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helpdesk_intake_forwards', to=settings.AUTH_USER_MODEL)),
                ('forwarded_to_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpdesk_intake_forwards', to='db.project')),
                ('intake_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpdesk_requests', to='db.intakeissue')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_links', to='db.helpdeskrequest')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Helpdesk Request Intake Issue',
                'verbose_name_plural': 'Helpdesk Request Intake Issues',
                'db_table': 'helpdesk_request_intake_issues',
                'unique_together': {('request', 'intake_issue', 'deleted_at')},
            },
        ),
    ]
