# Generated by Django 4.2.30 on 2026-06-17 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


# Legacy string → new status name mapping for data migration
LEGACY_STATUS_MAP = {
    "open": "Open",
    "in_progress": "In Progress",
    "waiting": "Waiting",
    "resolved": "Resolved",
    "closed": "Closed",
}

DEFAULT_HELPDESK_STATUSES = [
    {"name": "Open", "color": "#F97316", "sequence": 10000, "is_default": True},
    {"name": "In Progress", "color": "#3B82F6", "sequence": 20000, "is_default": False},
    {"name": "Waiting", "color": "#8B5CF6", "sequence": 30000, "is_default": False},
    {"name": "Resolved", "color": "#10B981", "sequence": 40000, "is_default": False},
    {"name": "Closed", "color": "#64748B", "sequence": 50000, "is_default": False},
]


def create_default_statuses_and_migrate(apps, schema_editor):
    Workspace = apps.get_model("db", "Workspace")
    HelpdeskStatus = apps.get_model("db", "HelpdeskStatus")
    HelpdeskRequest = apps.get_model("db", "HelpdeskRequest")

    for workspace in Workspace.objects.all():
        # Create the 5 default statuses for each workspace
        status_by_name = {}
        for s in DEFAULT_HELPDESK_STATUSES:
            obj = HelpdeskStatus.objects.create(
                id=uuid.uuid4(),
                workspace=workspace,
                name=s["name"],
                color=s["color"],
                sequence=s["sequence"],
                is_default=s["is_default"],
            )
            status_by_name[s["name"]] = obj

        # Migrate existing requests that still have the old string value
        # The field is now FK (null=True), raw SQL needed to read old value
        db_alias = schema_editor.connection.alias
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                "SELECT id, status_old FROM helpdesk_requests WHERE workspace_id = %s AND deleted_at IS NULL",
                [str(workspace.id)],
            )
            rows = cursor.fetchall()
            for row_id, legacy_status in rows:
                target_name = LEGACY_STATUS_MAP.get(legacy_status, "Open")
                status_obj = status_by_name.get(target_name)
                if status_obj:
                    cursor.execute(
                        "UPDATE helpdesk_requests SET status_id = %s WHERE id = %s",
                        [str(status_obj.id), str(row_id)],
                    )


def reverse_migration(apps, schema_editor):
    HelpdeskStatus = apps.get_model("db", "HelpdeskStatus")
    HelpdeskStatus.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0126_helpdeskrequestintakeissue_workspace_level'),
    ]

    operations = [
        # 1. Rename old status column so we can read it during data migration
        migrations.RenameField(
            model_name='helpdeskrequest',
            old_name='status',
            new_name='status_old',
        ),
        # 2. Create the new HelpdeskStatus model
        migrations.CreateModel(
            name='HelpdeskStatus',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(default='#60646C', max_length=20)),
                ('sequence', models.FloatField(default=65535)),
                ('is_default', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Helpdesk Status',
                'verbose_name_plural': 'Helpdesk Statuses',
                'db_table': 'helpdesk_statuses',
                'ordering': ['sequence'],
            },
        ),
        # 3. Add the new FK column (nullable)
        migrations.AddField(
            model_name='helpdeskrequest',
            name='status',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='requests',
                to='db.helpdeskstatus',
            ),
        ),
        # 4. Data migration: create defaults per workspace, map old values to new FK
        migrations.RunPython(create_default_statuses_and_migrate, reverse_migration),
        # 5. Remove the old string column
        migrations.RemoveField(
            model_name='helpdeskrequest',
            name='status_old',
        ),
    ]
