# Generated by Django 4.2.30 on 2026-06-17 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


DEFAULT_SUCCESS_MESSAGE = "Your request has been submitted successfully."


def create_default_helpdesk_forms(apps, schema_editor):
    HelpdeskPortal = apps.get_model("db", "HelpdeskPortal")
    HelpdeskForm = apps.get_model("db", "HelpdeskForm")
    HelpdeskFormField = apps.get_model("db", "HelpdeskFormField")

    for portal in HelpdeskPortal.objects.filter(deleted_at__isnull=True):
        form = HelpdeskForm.objects.create(
            id=uuid.uuid4(),
            workspace_id=portal.workspace_id,
            project_id=portal.project_id,
            portal=portal,
            name="Default request form",
            description="Default form used to submit requests to this portal.",
            slug="default-request-form",
            visibility="public",
            is_active=True,
            sequence=10000,
            success_message=DEFAULT_SUCCESS_MESSAGE,
        )

        HelpdeskFormField.objects.create(
            id=uuid.uuid4(),
            workspace_id=portal.workspace_id,
            project_id=portal.project_id,
            form=form,
            key="title",
            label="Subject",
            field_type="system_title",
            required=True,
            sequence=10000,
            is_system=True,
        )
        HelpdeskFormField.objects.create(
            id=uuid.uuid4(),
            workspace_id=portal.workspace_id,
            project_id=portal.project_id,
            form=form,
            key="description",
            label="Description",
            field_type="system_description",
            required=True,
            sequence=20000,
            is_system=True,
        )


def reverse_default_helpdesk_forms(apps, schema_editor):
    HelpdeskForm = apps.get_model("db", "HelpdeskForm")
    HelpdeskForm.objects.filter(slug="default-request-form").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0127_helpdesk_status_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="HelpdeskForm",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("slug", models.SlugField(max_length=255)),
                ("visibility", models.CharField(choices=[("public", "Public"), ("private", "Private")], default="public", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("sequence", models.FloatField(default=65535)),
                ("success_message", models.TextField(blank=True, default="")),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("portal", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="forms", to="db.helpdeskportal")),
                ("project", models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name="project_%(class)s", to="db.project")),
                ("updated_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL, verbose_name="Last Modified By")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="workspace_%(class)s", to="db.workspace")),
            ],
            options={
                "verbose_name": "Helpdesk Form",
                "verbose_name_plural": "Helpdesk Forms",
                "db_table": "helpdesk_forms",
                "ordering": ["sequence", "created_at"],
                "unique_together": {("portal", "slug", "deleted_at")},
            },
        ),
        migrations.CreateModel(
            name="HelpdeskFormField",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ("key", models.SlugField(max_length=255)),
                ("label", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("field_type", models.CharField(choices=[("system_title", "System Title"), ("system_description", "System Description"), ("short_text", "Short Text"), ("long_text", "Long Text"), ("select", "Select"), ("checkbox", "Checkbox"), ("date", "Date")], max_length=50)),
                ("placeholder", models.CharField(blank=True, default="", max_length=255)),
                ("help_text", models.TextField(blank=True, default="")),
                ("required", models.BooleanField(default=False)),
                ("sequence", models.FloatField(default=65535)),
                ("options", models.JSONField(blank=True, default=list)),
                ("validation", models.JSONField(blank=True, default=dict)),
                ("ui_props", models.JSONField(blank=True, default=dict)),
                ("is_system", models.BooleanField(default=False)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("form", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="fields", to="db.helpdeskform")),
                ("project", models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name="project_%(class)s", to="db.project")),
                ("updated_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL, verbose_name="Last Modified By")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="workspace_%(class)s", to="db.workspace")),
            ],
            options={
                "verbose_name": "Helpdesk Form Field",
                "verbose_name_plural": "Helpdesk Form Fields",
                "db_table": "helpdesk_form_fields",
                "ordering": ["sequence", "created_at"],
                "unique_together": {("form", "key", "deleted_at")},
            },
        ),
        migrations.AddField(
            model_name="helpdeskrequest",
            name="form",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="requests", to="db.helpdeskform"),
        ),
        migrations.AddField(
            model_name="helpdeskrequest",
            name="form_responses",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(create_default_helpdesk_forms, reverse_default_helpdesk_forms),
    ]
