# Generated by Django 4.2.30 on 2026-06-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0128_helpdesk_forms"),
    ]

    operations = [
        migrations.AddField(
            model_name="helpdeskportal",
            name="auto_assignment_config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="helpdeskportal",
            name="auto_assignment_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="helpdeskportal",
            name="auto_assignment_type",
            field=models.CharField(
                choices=[("load_balance", "Load Balance")],
                default="load_balance",
                max_length=50,
            ),
        ),
    ]
