# Generated by Codex on 2026-06-23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0136_seed_helpdesk_admins"),
    ]

    operations = [
        migrations.AddField(
            model_name="helpdeskrequest",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
