# Generated by Django 4.2.30 on 2026-06-24 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0138_helpdeskrequest_start_date_target_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpdeskmember',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='helpdeskportal',
            name='auto_assignment_type',
            field=models.CharField(choices=[('load_balance', 'Load Balance'), ('round_robin', 'Round Robin'), ('capacity', 'Capacity')], default='load_balance', max_length=50),
        ),
    ]
