# Generated by Django 4.2.30 on 2026-07-17 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0151_backfill_estimate_default_properties'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kpiconfig',
            options={'verbose_name': 'KPI Config', 'verbose_name_plural': 'KPI Configs'},
        ),
        migrations.AlterModelOptions(
            name='kpiissueattribute',
            options={'verbose_name': 'KPI Issue Attribute', 'verbose_name_plural': 'KPI Issue Attributes'},
        ),
        migrations.RemoveConstraint(
            model_name='estimateproperty',
            name='estimateproperty_unique_kpi_role_per_project',
        ),
        migrations.AddField(
            model_name='helpdeskportal',
            name='default_agent_email_address',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='helpdeskportal',
            name='no_reply_email_address',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='helpdeskrequestcomment',
            name='delivery_channels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='helpdeskrequestcomment',
            name='email_message_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='helpdeskrequestcomment',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='helpdeskrequestcomment',
            name='email_status',
            field=models.CharField(choices=[('not_sent', 'Not Sent'), ('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='not_sent', max_length=20),
        ),
        migrations.AlterField(
            model_name='estimateproperty',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='issueestimatepropertyvalue',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='kpiconfig',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='kpiissueattribute',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddConstraint(
            model_name='estimateproperty',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('kpi_role__isnull', False)), fields=('project', 'kpi_role'), name='estimateproperty_unique_kpi_role_per_project'),
        ),
    ]
