# Generated by Django 4.2.30 on 2026-07-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0152_alter_kpiconfig_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpdeskportal',
            name='smtp_host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='helpdeskportal',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='helpdeskportal',
            name='smtp_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='helpdeskportal',
            name='smtp_use_ssl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='helpdeskportal',
            name='smtp_use_tls',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='helpdeskportal',
            name='smtp_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
