# Generated by Django 4.2.30 on 2026-07-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0153_helpdeskportal_smtp_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpdeskrequestcomment',
            name='email_error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
