# Generated by Django 4.2.30 on 2026-07-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0155_helpdesk_email_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpdeskportal',
            name='max_attachment_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
