# Generated by Django 4.2.30 on 2026-07-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0156_helpdesk_portal_max_attachment_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpdeskrequestcomment',
            name='sender_verification',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('unverified', 'Unverified'), ('not_applicable', 'Not Applicable')], default='not_applicable', max_length=20),
        ),
    ]
