# Generated by Django 4.2.30 on 2026-07-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0157_helpdesk_comment_sender_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpdeskformfield',
            name='field_type',
            field=models.CharField(choices=[('system_title', 'System Title'), ('system_description', 'System Description'), ('short_text', 'Short Text'), ('long_text', 'Long Text'), ('select', 'Select'), ('checkbox', 'Checkbox'), ('date', 'Date'), ('cascade_select', 'Cascading Dropdown'), ('attachment', 'Attachment')], max_length=50),
        ),
    ]
