# Generated by Django manually

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('plane', '0158_helpdesk_form_attachment_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpdeskportal',
            name='is_imap_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='helpdeskportal',
            name='imap_host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='helpdeskportal',
            name='imap_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='helpdeskportal',
            name='imap_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='helpdeskportal',
            name='imap_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='helpdeskportal',
            name='imap_use_tls',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='helpdeskportal',
            name='imap_use_ssl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='helpdeskportal',
            name='imap_archive_folder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
