# Generated by Django 4.2.30 on 2026-07-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0161_helpdesk_imap_sync_logs_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpdeskrequest',
            name='priority',
            field=models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('none', 'None')], default='none', max_length=30, verbose_name='Helpdesk Request Priority'),
        ),
    ]
