# Generated by Django 4.2.30 on 2026-09-03.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0173_helpdesk_base_field_drift'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpdeskrequest',
            name='sla_first_response_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HelpdeskRequestRecurrence',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('match_type', models.CharField(choices=[('same_customer_similar', 'Same customer, similar problem'), ('shared_issue', 'Linked to the same work item')], max_length=50)),
                ('score', models.FloatField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('related_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_backlinks', to='db.helpdeskrequest')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_links', to='db.helpdeskrequest')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Helpdesk Request Recurrence',
                'verbose_name_plural': 'Helpdesk Request Recurrences',
                'db_table': 'helpdesk_request_recurrences',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='HelpdeskSLAPolicy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('none', 'None')], max_length=30)),
                ('first_response_hours', models.IntegerField(blank=True, null=True)),
                ('resolution_hours', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_policies', to='db.helpdeskportal')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Helpdesk SLA Policy',
                'verbose_name_plural': 'Helpdesk SLA Policies',
                'db_table': 'helpdesk_sla_policies',
                'ordering': ('portal', 'priority'),
                'unique_together': {('portal', 'priority', 'deleted_at')},
            },
        ),
        migrations.AddConstraint(
            model_name='helpdeskrequestrecurrence',
            constraint=models.CheckConstraint(check=models.Q(('request', models.F('related_request')), _negated=True), name='helpdesk_recurrence_no_self_link'),
        ),
        migrations.AlterUniqueTogether(
            name='helpdeskrequestrecurrence',
            unique_together={('request', 'related_request', 'match_type', 'deleted_at')},
        ),
    ]
